Implement 'customSignerURL' feature
internet-identity-labs/identitykit pull request #12
Opened 2024-07-04 18:48 UTC by vitaliipustovyi

2024-07-05 12:51 UTC, dmitriiIdentityLabs approved these changes

2024-07-15 18:58 UTC, dmitriiIdentityLabs approved these changes

2024-07-16 09:08 UTC, chorniy8pavlo requested changes

2024-07-16 09:08 UTC, chorniy8pavlo commented on packages/identitykit/src/libs/react/modal.tsx
> +                  <div>
I would put this in a separate react component

2024-07-16 09:08 UTC, chorniy8pavlo commented on packages/identitykit/src/libs/react/modal.tsx
> +                    <div className="text-l text-black font-bold my-[20px]">Custom Connect</div>
text-l ?

2024-07-16 09:08 UTC, chorniy8pavlo commented on package.json
> +    "react-hook-form": "^7.52.1"
I think all dependencies you've added should be in packages/identitykit/package.json.
Not in the root.

2024-07-16 11:40 UTC, chorniy8pavlo submitted a review, later dismissed

2024-07-16 11:40 UTC, chorniy8pavlo commented on packages/identitykit/src/libs/react/ui/input/index.tsx
> +export const CustomSignerInput = () => {
- Please put it on the same level as modal.tsx
- Rename file from `input.tsx` to `signer-input.tsx`

Reason for these - it's not a reusable input component it's a specific feature.

2024-07-16 11:48 UTC, chorniy8pavlo approved these changes

2024-07-16 12:07 UTC, merged